#lexik_jwt_authentication:
    #secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    #public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    #pass_phrase: '%env(JWT_PASSPHRASE)%'

lexik_jwt_authentication:
  secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers la clé privée
  public_key: '%kernel.project_dir%/config/jwt/public.pem' # Chemin vers la clé publique
  pass_phrase: 'votre_mot_de_passe'
  token_ttl: 3600 # Durée de validité du jeton (en secondes)
